name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'simplejwtapi-prod'    # Replace with your app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'            # Path to your web app project
  DOTNET_VERSION: '8.0.x'                   # .NET version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish application
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp

# To use this workflow:
# 1. Create an Azure App Service
# 2. Download the publish profile from Azure portal
# 3. Add it as a secret named 'AZURE_WEBAPP_PUBLISH_PROFILE' in GitHub
# 4. Update the AZURE_WEBAPP_NAME environment variable above
# 5. Push to main branch to trigger deployment